# Generated by Django 3.2.8 on 2021-10-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('units', models.IntegerField()),
                ('sales', models.IntegerField()),
                ('date_sold', models.CharField(max_length=100)),
            ],
        ),
    ]
